[package]
name = "efi-loader"
version = "0.1.0"
authors = ["Sergei Fomin <sergio-dna@yandex.ru>"]

[lib]
crate_type = ["staticlib"]

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
